language: node_js
node_js: 8
notifications:
  slack: airplane-mode:TKwbdTmN4XCcMRySy6ghJymU
before_script: npm run release
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: docs/_site
  github-token: $GITHUB_TOKEN
  project-name: Air Traffic Control
  verbose: true
